version: 1
logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: simple
      level: INFO
      stream: ext://sys.stdout
    file_handler:
      class: logging.handlers.RotatingFileHandler
      formatter: simple
      level: INFO
      filename: logs/myapp.log
      encoding: utf8
      maxBytes: 10485760 # 10 MB
      backupCount: 10 # Keep up to 10 backup files
  loggers:
    myapp:
      level: INFO
      handlers: [console, file_handler]
      propagate: no

reddit:
  client_id: 'client_id'
  client_secret: 'client_secret'
  user_agent: 'user_agent'
  redirect_url: 'redirect_url'

reddit_search:
  subreddit: 'data+analyst+data+science+data+engineering+IA+machine+learing'
  limit: 1 
  time_filter: 'week' # past hour, day, week, month, year, all

data_path:
  path_comments: /home/ay/DataEng/projects/reddit/data/comments
  path_posts: /home/ay/DataEng/projects/reddit/data/posts
  path_tmp: /home/ay/DataEng/projects/reddit/tmp
  path_project: /home/ay/DataEng/projects/reddit/

names_files_etl:
  extract: extract.py
  load: load.py
  transform: transform.py

