reddit:
  client_id: 'client_id'
  client_secret: 'client_secret'
  user_agent: 'user_agent'
  redirect_url: 'redirect_url'

reddit_search:
  subreddit: 'data+analyst+science+engineering+IA+machine+deep+learing+chatgpt+big+data'
  limit:
  time_filter: 'week' # past hour, day, week, month, year, all

data_folder_bucket: gs://extract-data-reddit/data
file_format: '%Y-%m-%d %H:%M:%S'
