version: 1
logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: simple
      level: INFO
      stream: ext://sys.stdout
    file_handler:
      class: logging.handlers.RotatingFileHandler
      formatter: simple
      level: INFO
      filename: logs/myapp.log
      encoding: utf8
      maxBytes: 10485760 # 10 MB
      backupCount: 10 # Keep up to 10 backup files
  loggers:
    myapp:
      level: INFO
      handlers: [console, file_handler]
      propagate: no

reddit:
  client_id: 'client_id'
  client_secret: 'client_secret'
  user_agent: 'user_agent'
  redirect_url: 'redirect_url'

reddit_search:
  subreddit: 'data+analyst+science+engineering+IA+machine+deep+learing+chatgpt+big+data'
  limit: 1000000000
  time_filter: 'week' # past hour, day, week, month, year, all

s3:
  access_key: 'ACCESS_KEY'
  secret_key: 'SECRET_ACCESS_KEY'
  src_endpoint_url: 'https://s3.amazonaws.com'
  src_bucket: 'pde-data-reddit'
  trg_endpoint_url: 'https://s3.amazonaws.com'
  trg_bucket: ''

folder_bucket:
  comment_folder: 'comments'
  post_folder: 'posts'


data_path:
  path_comments: /home/ay/DataEng/projects/reddit/data/comments
  path_posts: /home/ay/DataEng/projects/reddit/data/posts
  path_tmp: /home/ay/DataEng/projects/reddit/tmp
  path_project: /home/ay/DataEng/projects/reddit/

names_files_etl:
  extract: extract.py
  load: load.py
  transform: transform.py

